# Generated by Django 3.1.7 on 2021-03-18 19:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210316_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.courier')),
            ],
        ),
    ]
